version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: safestep-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safestep-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      # If you have real Supabase, set SUPABASE_URL and SUPABASE_KEY here instead of using local Postgres only
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      SECRET_KEY: ${SECRET_KEY:-change-me-in-prod}
      # Optional Supabase placeholders (leave empty if not using)
      SUPABASE_URL: ${SUPABASE_URL:-}
      SUPABASE_KEY: ${SUPABASE_KEY:-}
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./SafeStep/prediction
        target: /app/prediction
      - type: volume
        source: instance_data
        target: /app/instance
    restart: unless-stopped

volumes:
  db_data:
  instance_data: