version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: safestep-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - web
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safestep-web-prod
    environment:
      # Production Supabase Configuration
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_ENV: production
      # Optional AI Features
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      # Session Security
      SESSION_COOKIE_SECURE: "true"
    expose:
      - "5000"
    volumes:
      - type: bind
        source: ./SafeStep/prediction
        target: /app/prediction
      - type: volume
        source: instance_data
        target: /app/instance
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  instance_data: