[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p instance']

[start]
cmd = 'python SafeStep/wsgi.py'

[variables]
PORT = '8080'
