services:
  - type: web
    name: safestep-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd SafeStep && python deploy.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000
